style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140

comments:
  active: false

complexity:
  TooManyFunctions:
    thresholdInFiles: 20

naming:
  FunctionNaming:
    ignoreAnnotated: ["Composable"]
